config/routes.rb
Rails.application.routes.draw do
  resources :goals do 
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
  
  resources :statics
  root 'goals#index'
  devise_for :users
  resources :users, except: [:new]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :tasks
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  
  belongs_to :goal
  
  def completed?
    !date_complete.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end
  def yourgoals
    @goals = current_user.goals
  end
  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save
      redirect_to goals_path
    else
      redirect_to new_goal_path
    end
    
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:title, :description, :date_due, :user_id)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: [:show, :edit, :update, :destroy]

  # GET /statics
  # GET /statics.json
  def index
    @statics = Static.all
  end

  # GET /statics/1
  # GET /statics/1.json
  def show
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics
  # POST /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to @static, notice: 'Static was successfully created.' }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1
  # PATCH/PUT /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to @static, notice: 'Static was successfully updated.' }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1
  # DELETE /statics/1.json
  def destroy
    @static.destroy
    respond_to do |format|
      format.html { redirect_to statics_url, notice: 'Static was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_params
      params.require(:static).permit(:home)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]
  before_action :set_goal, only: [:show, :edit, :update, :destroy, :create, :complete]

 
  def index
    @tasks = Task.all
  end

 
  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  
  def create
    @task = @goal.tasks.create(task_params)
    redirect_to goal_path(@goal)
  end


  def update
  end


  def destroy
    @task = @goal.tasks.find(params[:id])
    if @task.destroy
      flash[:success] = "Task deleted"
    else
      flash[:error] = "Error"
    end
    redirect_to @goal
  end
  
  def complete
    @task.update_attribute(:date_complete, Time.now)
    redirect_to @goal, notice: "Task completed"
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end
  
    def set_goal
      @goal = Goal.find(params[:goal_id])
    end

    def task_params
      params.require(:task).permit(:name, :complete, :task_due)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :goal_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :goal_description %>
  </div>

  <div class="field">
    <%= form.label :date_due %>
    <%= form.date_select :date_due, id: :goal_date_due %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.title %></td>
        <td><%= goal.description %></td>
        <td><%= goal.date_due %></td>
        <td><%= goal.user.email %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Belongs to:</strong>
  <%= @goal.user.email %>
</p>
<p>
  <strong>Title:</strong>
  <%= @goal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Date due:</strong>
  <%= @goal.date_due %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

<hr>

<center><h1>Tasks</h1></center>

<div>
  <%= render @goal.tasks %>
</div>

<hr>

<div>
  <%= render 'tasks/form' %>
</div>

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
      data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    
    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "All Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              Placeholder</li> 
            </ul>
          </li>
          
          <% if user_signed_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Goals <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "New Goal", new_goal_path %></li>
                  <li><%= link_to "All Goals", goals_path %></li>

                  <li role="separator" class="divider"></li>
              </ul>
            </li>
          <% end %>

        </ul>

 

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              
            <%= current_user.email.capitalize %>  <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Account", edit_user_registration_path %> </li>
                <li> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>   
        <% else %>
                <li> <%= link_to "Sign up", new_user_registration_path %></li>      
                <li> <%= link_to "Log in", new_user_session_path %></li>      
        <% end %>
              </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/statics/_form.html.erb
<%= form_with(model: static, local: true) do |form| %>
  <% if static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
      <% static.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :home %>
    <%= form.text_field :home, id: :static_home %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statics/edit.html.erb
<h1>Editing Static</h1>

<%= render 'form', static: @static %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statics</h1>

app/views/statics/new.html.erb
<h1>New Static</h1>

<%= render 'form', static: @static %>

<%= link_to 'Back', statics_path %>

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home:</strong>
  <%= @static.home %>
</p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>

app/views/tasks/_form.html.erb
<%= form_for([@goal, @goal.tasks.build]) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>



  <div class="field">
    <%= form.label :task_due %>
    <%= form.date_select :task_due, id: :task_task_due %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% if task.completed? %>

  <b><p><%= task.name %></b> was completed on: <b><%= task.date_complete %></b> | 
  <%= link_to "", goal_task_path(@goal, task.id),
  method: :delete, data: {confirm: "Are you sure you want to delete this?"}, class: "glyphicon glyphicon-trash" %>  | 
  <%= link_to "",  complete_goal_task_path(@goal, task.id), method: :patch, class: "glyphicon glyphicon-ok" %></p>
<% else %>
  <b><p><%= task.name %></b> is due on <b><%= task.task_due %></b> | 
  <%= link_to "", goal_task_path(@goal, task.id),
  method: :delete, data: {confirm: "Are you sure you want to delete this?"}, class: "glyphicon glyphicon-trash" %>  | 
  <%= link_to "",  complete_goal_task_path(@goal, task.id), method: :patch, class: "glyphicon glyphicon-ok" %></p>
<% end %>
<hr>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Complete</th>
      <th>Task due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.complete %></td>
        <td><%= task.task_due %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<p>
  <strong>Task due:</strong>
  <%= @task.task_due %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>